name: VPS Auto SSH

on:
  workflow_dispatch:

jobs:
  create-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server qemu-system-x86 cloud-utils

      - name: Create disk image
        run: |
          qemu-img create -f qcow2 vps.img 10G
          cloud-localds cloud.img user-data

      - name: Start VPS
        run: |
          nohup qemu-system-x86_64 \
            -m 2048 \
            -smp 2 \
            -hda vps.img \
            -net nic -net user,hostfwd=tcp::2222-:22 \
            -nographic &
          sleep 20

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          cat ~/.ssh/id_rsa.pub

      - name: Connect to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 user@127.0.0.1 "echo 'SSH Connected to VPS'"
